CC=clang
CFLAGS=-Wall -Wextra -Werror
COLLEEN=Colleen
GRACE=Grace
SULLY=Sully

.PHONY: clean

all: $(COLLEEN) $(GRACE) $(SULLY)

fclean: clean
	rm -rf $(COLLEEN) $(GRACE) $(SULLY)

re: fclean
	$(MAKE)